name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  validate_fuzz_target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install cargo-fuzz
      - run: cargo fuzz build validate --sanitizer none
      - run: cargo fuzz run validate --sanitizer none -- -max_total_time=60

  validate_swarm_fuzz_target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install cargo-fuzz
      - run: cargo fuzz build validate-swarm --sanitizer none
      - run: cargo fuzz run validate-swarm --sanitizer none -- -max_total_time=60

  validate_ensure_terminated_fuzz_target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install cargo-fuzz
      - run: cargo fuzz build validate-ensure-termination --sanitizer none
      - run: cargo fuzz run validate-ensure-termination --sanitizer none -- -max_total_time=60

  check_benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo check --benches
